### ISSUE TITLE
OSError: [Errno -9981] Input overflowed

### ISSUE THREAD

**Issue by mKenfenheuer** [Ant-Brain/EfficientWord-Net#22]
I've installed the python library with

`pip install EfficientWord-Net`

onto a raspberry pi 2 with recent raspbian lite.

However if i run the demo with `python -m eff_word_net.engine` i'll get the following error and nothing works:

```
Say Mycroft / Alexa / Siri
Traceback (most recent call last):
  File "/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/max/.local/lib/python3.9/site-packages/eff_word_net/engine.py", line 333, in <module>
    frame = mic_stream.getFrame()
  File "/home/max/.local/lib/python3.9/site-packages/eff_word_net/streams.py", line 49, in getFrame
    new_frame = self._get_next_frame()
  File "/home/max/.local/lib/python3.9/site-packages/eff_word_net/streams.py", line 85, in <lambda>
    np.frombuffer(mic_stream.read(CHUNK),dtype=np.int16)
  File "/usr/lib/python3/dist-packages/pyaudio.py", line 608, in read
    return pa.read_stream(self._stream, num_frames, exception_on_overflow)
OSError: [Errno -9981] Input overflowed
```

any idea?

**Comment by TheSeriousProgrammer** [comment]
Sorry about the late reply, i am unable to reproduce the error, what mic are you using, it is advised to use a mic with defaut 16khz sampling frequency

**Comment by TheSeriousProgrammer** [comment]
Closing as issue is inactive, and unable to reproduce, kindly reopen if required
