### ISSUE TITLE
Problem with Dependencies

### ISSUE THREAD

**Issue by Balro76** [Ant-Brain/EfficientWord-Net#6]
Hello
I left a comment on Reddit saying I would give it a go, and you said if I had a problem to log it here, so here I am, with a problem 😊

I seem to get stuck with   pip3 install librosa
I get this error
Failed building wheel for llvmlite
  Running setup.py clean for llvmlite
Failed to build llvmlite
I can push on and get EfficientWord installed and working, if I say Alexa it says Yup I hear ya

The problem is then when I try to create my own wake word I run this command …
python3 -m eff_word_net.generate_reference
pi@raspberrypi:~ $ python3 -m eff_word_net.generate_reference
Paste Path of folder Containing audio files:/home/pi/wakewords
Paste Path of location to save *_ref.json :/home/pi/wakewords
Enter Wakeword Name                                 :bender
Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/pi/.local/lib/python3.7/site-packages/eff_word_net/generate_reference.py", line 80, in <module>
    input("Enter Wakeword Name                                 :")
  File "/home/pi/.local/lib/python3.7/site-packages/eff_word_net/generate_reference.py", line 47, in generate_reference_file
    x,_ = librosa.load(audio_file,sr=16000)
AttributeError: module 'librosa' has no attribute 'load'

My Problem is with librosa, I am not able to install it. I tried everything I could google but it will never install

How did you get around this problem ?

**Comment by TheSeriousProgrammer** [comment]
are you using mac M* series ,except that for all platforms librosa binaries (whls) are available
Sorry for the late reply though

**Comment by aman-17** [comment]
You need to install a few pre-requisites which are mentioned in the read.me, pyaudio is one of them :)

**Comment by pythonbrad** [comment]
Hi @TheSeriousProgrammer, is it this issue still open?

I wrote a dockerfile that I can share.
This is my idea

---

**Commands**

Transcribe an audio.

```sh
docker run -v audio.mp3:/audio.mp3 --rm -it test transcribe /audio.mp3
```

Generate reference files.

```sh
docker run -v wakewords/input:/input -v wakewords/output:/output --rm -it test generate --input-dir /input --output-dir /output --wakeword mobile --model-type resnet_50_arc
```
